### ISSUE TITLE
0.26.18: TS type check error - declares 'Derivable' locally, but it is not exported

### ISSUE THREAD

**Issue by jlowcs** [floating-ui/floating-ui#2951]
When updating to 0.26.18, TS compilation results in the following error:

```sh
node_modules/@floating-ui/react/dist/floating-ui.react.d.mts:16:10 - error TS2459: Module '"@floating-ui/react-dom"' declares 'Derivable' locally, but it is not exported.

16 import { Derivable } from '@floating-ui/react-dom';
            ~~~~~~~~~

  node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.d.mts:13:10
    13 import { Derivable } from '@floating-ui/dom';
                ~~~~~~~~~
    'Derivable' is declared here.
```

**Comment by atomiks** [comment]
Are `@floating-ui/dom` and `@floating-ui/core` are updated to latest?
