### ISSUE TITLE
Issue with vitest

### ISSUE THREAD

**Issue by herzaso** [floating-ui/floating-ui#3253]
I was using floating-ui 0.26.25 in with the following stack:
react 17.0.2
typescript 5.1.3
vite 4.4.9
vitest 0.34.6

After bumping the version to 0.27.5, my tests are failing with the following error:
```
Cannot find module '.../node_modules/react/jsx-runtime' imported from .../node_modules/@floating-ui/react/dist/floating-ui.react.mjs
Did you mean to import react/jsx-runtime.js?
```

(my app does run in the browser)

**Comment by atomiks** [comment]
When running it in native Node, appending `.js` to `react/jsx-runtime` for the `.mjs` dist file fixes it, it seems

(Upgrading your Vite/Vitest dependencies may fix the issue though, as I haven't seen this happen with the latest versions?)

**Comment by herzaso** [comment]
bumping major versions in not an option since this is in a very large project and stability is crucial.
I'm not sure how to add that configuration. Is that 'alias'?

**Comment by herzaso** [comment]
problem seems to persist with vite 6.2.1 + vitest 3.0.8

**Comment by atomiks** [comment]
Vitest fix:

```js
test: {
  deps: {
    inline: [/@floating-ui/],
  },
}
```

Webpack 5 fix (4 is ok):

```js
resolve: {
  alias: {
    "react/jsx-dev-runtime": "react/jsx-dev-runtime.js",
    "react/jsx-runtime": "react/jsx-runtime.js"
  }
}
```

https://github.com/radix-ui/primitives/issues/2974#issuecomment-2186808459

**Comment by herzaso** [comment]
works well, thanks!
